name: consul-elopio
version: master
summary: Consul is a tool for service discovery, monitoring and configuration
description: |
  Consul is distributed, highly available, and extremely scalable.
  Consul provides service discovery, health checking, key/value storage and
  multi-datacenter.
confinement: strict

apps:
  consul:
    command: consul-snap
    plugs: [network, network-bind, network-observe, tools]

plugs:
  tools:
    interface: content
    content: healthcheck-toolbox
    target: tools
    default-provider: healthcheck-toolbox-example:toolbox

parts:
  consul:
    source: https://github.com/hashicorp/consul.git
    source-tag: master
    plugin: go
    go-importpath: github.com/hashicorp/consul
    after: [go1.7]
  script:
    source: .
    plugin: dump
    snap: ["consul-snap", "tools"]
  go1.7:
    plugin: nil
    build-packages: [golang-go]
    source: https://go.googlesource.com/go
    source-type: git
    source-tag: go1.7.5
    build: cd src && env GOROOT_BOOTSTRAP=$(go env GOROOT | tr -d '\n') ./make.bash
    install: cp -R * $SNAPCRAFT_PART_INSTALL
    prime:
      - '-*'
